name = "Thunks"
uuid = "490da00b-a60c-4ded-a4cf-df7cded56bfa"
authors = ["Tyler Benster <thunk@tylerbenster.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
